### ISSUE TITLE
Issues are not loading in atom

### ISSUE THREAD

**Issue by mmcintyre123** [amiuhle/atom-redmine#3]
After enterring the command to open all issues, a box appears at the top that says "Loading issues ...", but the issues never load.  I am fairly sure the installation is setup correctly as enterring the command to open the project correctly opens the project page in my browser.  Please let me know if any additional information is needed....
![2015-06-09_15-33-55](https://cloud.githubusercontent.com/assets/12388285/8067702/7c47611e-0ebd-11e5-929a-b08598a9b1fa.png)

**Comment by amiuhle** [comment]
Yes, I'm afraid I need more information.
Is it possible to add an account for me in your Redmine installation so I can test it?

**Comment by amiuhle** [comment]
Does the console log an error?

**Comment by anatooly** [comment]
1) I have problem like http -> redirect to https (header x-redmine-api-key lost).

Unhandled promise rejection Promise with error: SyntaxError: Unexpected token <index.js:14 (anonymous function)events.js:87 emitTwoevents.js:169 emitnode.js:422 emitPendingUnhandledRejectionsnode.js:342 runMicrotasksCallbacknode.js:357 _tickCallback

I manual edit plugin like (fetch-redmine.js):

```
this.baseUrl = `https://${config.host}`;
```

add https url and all work fine. I think need minimum special checkbox on settings for this.

2) When I see request on server never see my limit param or statusId=close
I think for .atom-redmine need use all http://www.redmine.org/projects/redmine/wiki/Rest_Issues parameters. 

3) When I click on issue it open browser but baseUrl link not my selected bug. I think need open on new tab only issue text for reading that all. Change to https this place issues-list-view.js for correct link:

confirmed(item) {
    shell.openExternal(`https://

4) Need command like 'Redmine _issue number_' for fast open in browser.

Thx.

**Comment by bajzarpa** [comment]
I have the same problem. But my console shows `Access-Control-Allow-Origin` errror however we enabled the jsonp support in the redmine. And of course we also enabled te REST service as well. 

Printscreen:
![image](https://cloud.githubusercontent.com/assets/943893/10242095/81f57c96-68ee-11e5-9043-6c6c2f8590a0.png)

**Comment by bajzarpa** [comment]
**update:**
We figured out what was the problem. If you don't want the pain of the jsonp. Just install the following redmine plugin: https://github.com/mavimo/redmine_cors and after this your plugin will work

**Comment by amiuhle** [comment]
Sorry guys, don't have a lot of time right now. I'll get to it as soon as possible!

**Comment by amiuhle** [comment]
@anatooly That's unrelated in this ticket. If you want, you can write a new one, but I'll be adding more config options for the next release anyways.

CORS problems should be fixed.
